version: '3'

services:

  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=raviyax.me
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    image: wordpress:6.4.0-php8.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=raviyax.me
    working_dir: /var/ridehub/html
    volumes:
      - wordpress:/var/ridehub/html
    networks:
      - app-network



  iqube:
    build: ./app
    depends_on:
      - db
    container_name: iqube
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./iqube:/var/iqube/html/
    networks:
      - app-network

  pma:
    build: ./pma
    depends_on:
      - db
    container_name: pma
    restart: unless-stopped
    networks:
      - app-network
    env_file: .env
    volumes:
      - pma:/var/pma/html/
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 50M

  webserver:
    depends_on:
      - pma
      - wordpress
      - iqube
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress:/var/ridehub/html
      - pma:/var/pma/html/
      - ./iqube:/var/iqube/html/
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
    networks:
      - app-network

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - app-network


volumes:
  wordpress:
  dbdata:
  pma:
  iqube:


networks:
  app-network:
    driver: bridge
