version: '3'

services:

  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=raviyax.me
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    image: wordpress:6.4.0-php8.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=raviyax.me
    volumes:
      - wordpress:/var/ridehub/html
    networks:
      - app-network

  iqube:
    build: ./application
    depends_on:
      - db
    container_name: iqube
    restart: unless-stopped
    env_file: .env
    volumes:
      - iqube:/var/iqube/html
    networks:
      - app-network

  phpmyadmin:
    build: ./phpmyadmin
    depends_on:
      - db
    container_name: phpmyadmin
    restart: unless-stopped
    networks:
      - app-network
    env_file: .env
    volumes:
      - pma:/var/pma/html/
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 50M

  webserver:
    depends_on:
      - phpmyadmin
      - wordpress
      - iqube
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress:/var/ridehub/html
      - pma:/var/pma/html/
      - iqube:/var/iqube/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
    networks:
      - app-network

  certbot-renew:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot-renew
    volumes:
      - certbot-etc:/etc/letsencrypt
      - wordpress:/var/ridehub/html
      - pma:/var/pma/html/
      - iqube:/var/iqube/html
    command: renew


volumes:
  certbot-etc:
  wordpress:
  dbdata:
  pma:
  iqube:


networks:
  app-network:
    driver: bridge
